api_platform:
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
        html: ["text/html"]
    docs_formats:
        jsonld: ["application/ld+json"]
        jsonopenapi: ["application/vnd.openapi+json"]
        html: ["text/html"]
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        pagination_client_enabled: true
        pagination_client_items_per_page: true

    # Voici la partie magique pour le bouton Authorize :
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
