services:
  database:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boutique_informatique
      MYSQL_USER: app
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data: